sudo: required

language: cpp # we run all tests in docker container so this can be anything

services:
  - docker

before_install:
  - make docker-image

script:
  - make docker
  - TAI_DOCKER_CMD='make test' make cmd
  - TAI_DOCKER_CMD='make -C tools/taish' make cmd
  - TAI_DOCKER_CMD='make -C tools/framework/examples/stub' make cmd
  - TAI_DOCKER_CMD='make -C tools/framework/examples/basic' make cmd
