cc_library(
    name = "stub_tai",
    srcs = [
        "stub_tai.c",
    ],
    deps = [
        "//:metatai",
    ],
    copts = [
        "-fPIC",
    ],
    visibility = [ '//visibility:public' ],
)